name: build-linux

on:
  push:
  release:
    types: [published]
  pull_request:
    types: [opened, edited, synchronize, reopened]

jobs:
  build:
    name: Linux (GCC)
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v5
        with:
          submodules: recursive

      - name: Install Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            cmake \
            gcc \
            g++ \
            ninja-build \
            libgtk-3-dev \
            libglu1-mesa-dev \
            libgl1-mesa-dev \
            libx11-dev \
            libxext-dev

      - name: Configure
        run: cmake -S . -B build -DCMAKE_BUILD_TYPE=Release -DINSTALL_DEPS=ON

      - name: Build
        run: cmake --build build -j$(nproc)

      - name: Upload executable artifact
        uses: actions/upload-artifact@v4
        with:
          name: gpu_demo_linux
          path: |
            build/gpu_demo
